# Generated by Django 5.2.4 on 2025-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_product_category_products_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
