# Generated by Django 5.2.4 on 2025-07-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_alter_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
