# Generated by Django 5.2.4 on 2025-07-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_order_id_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='', max_length=50)),
                ('order_status', models.CharField(default='', max_length=50)),
                ('update_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
